---
title: "Final Grade Reflection"
author: "Anagha Sikha"
format: docx
editor: visual
---

(All evidence can be found in supporting_artifacts \> learning_targets \> referenced file) I have demonstrated proficiency in **WD-1:** importing data from variety of formats. In Practice Activity 4 Question 1, I imported data from an xlsx sheet, and in Lab 4 "Reading the Data into R", I imported data from a csv file. In Lab 4 Question 3, I have demonstrated proficiency in **WD-2**: selecting necessary columns from a dataset, **WD-3**: filtering rows from a data frame for a variety of datatypes, and **DVS-4:** calculating numerical summaries of variables. I used a semi-join on a dataset I created containing the regions in order focus on the region data in the avocado dataset. I also used a filter on a integer and character variable and used select() to select the two variables the question was asking about, region and small HASS avocados. I used summarize to calculate the highest small HASS avocado sale with max(), and through Lab 4 Question 5 and 6, I was able to use summarize to find the sum and mean of the total volume of avocados. I also used anti_joins in Lab 4 Question 2 to create the city dataset by making sure it didn't include the region and state data through the anti_joins. In Lab 4 Question 7, I demonstrated proficiency in **WD-4**: modifying existing variables and creating new variables in a dataframe for a variety of data types, in **R-3**: writing robust programs that are resistant to changes in input, and in **R-2:** writing well documented and tidy code. Here I used mutate to create new numeric variables like prop_small, prop_large, and prop_xl using other numeric variables in the dataframe. I also used mutate to modify existing character variables by using fct_recode and fct_relevel to rename and relevel the proportion sizes variables. The way I wrote the code for question 7 is resistant to change because I used variable names rather than the positions when selecting the columns, and also creating unique variable names in the mutate. This code is tidy with white spaces after every comma, new lines after every '\|\>', splitting up large commands like in summarize(), mutate(), pivot_longer(), and including the resources in comments. I chose question 7 because it was a difficult question that I had to revise in office hours, and I am proud of the cleaned up result that is more effective and tidier than the first couple of tries. In Lab 5 "Captures over the Week" Question 3, I demonstrated proficiency in **DVS-1:** creating visualizations for a variety of variable types, **DVS-2**: using plot modifications to make visualizations clearer to the readers, **DVS-3**: showing creativity in my visualizations, and **DVS-5:** finding summaries of variables across multiple groups. This question displays a stacked bar plot of a categorical (Weekday, Weekend) vs quantitative variable (Number of Rodents). Additionally in Lab 5 Question 2-4 and Revisiting Lab 2, I created time series line graphs and a boxplot. I used plot modifications to remove the x and y axis and create an effective title graph to make the visualization clearer for the reader. I showed my creativity in this question by incorporating a ghibli palette color scheme to fill in the stacked bar plot. I also showed by creativity by coloring the jitterpoints in the boxplot purple. In Lab 5 "Time Series Plot" Question 4, I demonstrated proficiency in **DVS-5:** finding summaries of variables across multiple groups, by grouping year and genus, and applying summarize to calculate the mean weight across these groups. In Lab 5 Set Up, I use the here package to load in the data and not show any message. In my YAML set up my quarto document to be professional looking with a theme and having code-folds. I have demonstrated a commitment to continued learning by trying my best in the Lab, Challenge, Preview Activity, and Practice Activity. Through these assignments, I get to extend my thinking beyond what I learned in class by incorporating my creativity on aspects of the Challenge. For example, I wanted to attempt all 3 levels in Challenge 2 because they all taught me something new and I wanted to learn more about colors in plots since I find that very fascinating. I was able to learn more about hex codes and select my own color palette for that Challenge. Additionally, I show my ability to revise my thinking through submitting revisions on labs and challenges and through revising code that receives an S but has comments. For example, in my Lab 1 and Lab 2 I received comments about removing messages and changing the axis label and did not have to submit a revision for those sections. However, I found it important to improve those parts of my lab, and learned how to remove the messages and write a clearer axis label. This was helpful and important, as the next lab required me to incorporate those improvements, and I was able to prevent a repeat of my mistakes. I have also attended office hours to get extra help on problems that I had difficulty with revising such as Lab 4 Question 7. Through the extra help, I was able to understand more about how to organize the code to be more efficient and understand where I went wrong. I also included reflections along all my revisions, which has helped me think about the process of how I improved my code and learned from my mistakes. I have grown as a team member by working together with my team to solve each question in the labs. I have listened to my teammates when they have questions, and try my best to support and help them find the answer. During class I have asked Dr. Theobold and Bella team questions and contribute in our group chat where we help each other outside of class. Additionally, I have grown as a team member by providing feedback on the tidiness and efficiency of a classmate\'s code, making sure to provide praise on something that was done well and. I have contributed to creating a respectful classroom learning environment by listening and not judging other students\' questions, as they can be clearing up confusions me and other students may have. I have contributed to creating a respectful classroom learning environment by being kind to my classmates and not causing disruptions during class. At the start of the course, I wanted to be open-minded when learning the language R as coding can be difficult, and it is important to be patient and learn multiple different ways to solve problems. I believe that I am successful in staying open-minded and patient while I have been learning R and participating in the class, as I take the time to learn the new skills from Preview Activities. I also ask questions to the professor, learning assistant, and other students to make sure I understand the topics. As the topics have gotten harder, I have made sure to allocate more time towards the class to understand the notes, videos, and lecture slides. When I come across questions, I make sure to ask them right away to prevent any doubts from lingering. As the course goes on, I believe I will continue to be able to accomplish my goals. I believe I have earned an A so far in STAT 331. I have demonstrated proficiency for the majority of the learning targets that we have learned so far, revised code from my labs and challenges when the opportunity was given, have extended my thinking to all the Challenge assignments, and have taken risks by completing tasks that I did not know would be correct. I communicate with my team and Dr. Theobold, asking questions when there are confusions, and asking for additional help in office hours and in the Discord. I have been present, respectful, prepared for class and completed all of the assignments. 

\
