---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Describe how you have improved as a practitioner and student of data science this quarter through your work in the course. Focus specifically on data science concepts and the skills we employed in learning them. Don\'t just give a laundry list of topics that you learned (those are in the syllabus, so we know them already). Focus instead on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth. Explain in this essay how this artifact shows growth in the way you are describing.\

I believe Lab 4 shows my growth as a Data Scientist because this was the most difficult Lab for me, and I believe that the experience I went through to complete and revise this lab really embodies what data science is. In this lab I experienced not understanding the question properly resulting in submitting the code that was incorrect as it did not answer the question correctly. I also experience collaborating with my classmates, as I recall this lab my classmates and I were explaining how we each thought to answer the questions and trying to improve from each others ideas. This lab also demonstrates asking for help as I went to office hours to understand from my mistakes and collaborate with Dr. Theobold and another classmate to solved Question 6 and 7. From this experience, I was able to properly understand a concept that I was struggling with (pivoting datasets), and gain confidence in using it correctly in future labs.

From this lab, I was able to improve on my creativity and logical thinking, as I had the right ideas in Lab 4 but struggled with implementing them. After this lab, I was able to implement our class concepts in the future labs better.
