---
title: "The Power of Efficiency"
format: html
editor: visual
---

Efficiency is being productive and successful without having to lose a lot of time or effort. In statistical computing, being efficient can refer to writing code that does not repeat or that is not more confusing than it has to be. Being efficient in statistical computing can result in writing functions and using iteration to prevent repetition. It can also refer to using the most up-to-date functions to make sure that proper code is being run, and that the computer is not taking more time to run code than it needs to be by using out-of-date code. Being efficient in statistical computing allows one code to run faster and better, and it allows others who read your code to understand it more easily as it most likely will be shorter without any unnecessary repetition or complicated code. Efficiency is important because it saves you time and energy. Writing code that is unnecessarily long and repetitive makes your life more difficult as it can be harder to find bugs if errors occur and makes it more difficult for others to understand. Therefore, to make your own life and others' lives easier, it is better to be more efficient and makes you a better data scientist to learn the most efficient methods.

I encountered efficiency when learning about functions that would prevent us from taken multiple steps to get the same result such as slice_max and slice_min. Rather than arranging your data and then using slice_head, I learned to call slice_max or slice_min to get the highest or lowest data rows. This can be seen in Lab 4 Question 6 where I wanted the city with the largest price difference, and I found this by calling slice_max and ordering by price_diff. An a-ha moment I had with efficiency was early on in the quarter where we learned about pipelines. This reduced the amount of times we would have to repeat using the data frame as we could combine all the functions we wanted to apply on the data frame in one pipeline. This can be seen in any lab or challenge in the learning_targets or extended_learning folder, where the code chunks use pipelines to mutate, summarize, filter, join, and plot data sets. Another a-ha moment was learning about functions. In Challenge 8, I was able to create functions in order to display the lyrics to a song for a given day. I was amazed how this code in the one singular was able to iterate through every day and make the changes to the various different inputs without having to create new code for each type of input. By having a 'pluralize_gift' , 'make_phrase', and 'sing_line_option3' function that covered every case, we were able to input the whole 12 Days of Christmas and properly pluralize and display it.
